auth:
  jwt:
    secret: ${JWT_SECRET}

spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PDB_URL}
    username: ${PDB_USER}
    password: ${PDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

  #aws
  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      region:
        static: ap-northeast-2
      stack:
        auto: false
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}

  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.indayvidual: INFO

kakao:
  api-base: https://kapi.kakao.com
  oauth:
    client-id:       ${KAKAO_REST_API_KEY}
    client-secret:   ${KAKAO_CLIENT_SECRET:}   # 없으면 빈 값
    token-info-uri:  https://kapi.kakao.com/v1/user/access_token_info
    user-info-uri:   https://kapi.kakao.com/v2/user/me

app:
  profile:
    default-image-url: https://indayvidual.s3.ap-northeast-2.amazonaws.com/base_image.png