name: Sync Labels

on:
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync labels to this repo only
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml  
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
